### PR TITLE
Prevent ifelse from returning zero-bit DistInt

### PR DESCRIPTION
**Pull request by rtjoa**

### CODE REVIEW

**Comment by guyvdbroeck** [comment]
Thanks. Can you perhaps add a unit test that checks for this bug?

**Comment by rtjoa** [comment]
> Thanks. Can you perhaps add a unit test that checks for this bug?

Added in 84b9d68!

**Comment by guyvdbroeck** [comment]
Thanks. I am wondering whether it makes more sense to make the bit width a type parameter and require the same bit width in the then and else branches? @PoorvaGarg ?

**Comment by guyvdbroeck** [comment]
merging this for now but still confused why bit width would ever reduce. seems to me like the returned bit width should be the max of the two arguments of the iften

**Comment by rtjoa** [comment]
> merging this for now but still confused why bit width would ever reduce. seems to me like the returned bit width should be the max of the two arguments of the ifthen

My understanding is that if the most significant *k* bits are unsatisfiable, then they are "chopped off" the returned DistInt. Here is the [relevant code](https://github.com/Juice-jl/Dice.jl/pull/6/commits/fbe679682686034f12ac305507d43830b2cda084#diff-eb59847a020bcf729bfb27a1eb6dbcc5eec5eafa7f98e985e87786075183c7b0R74-R98) with some additional comments:
```julia
function ifelse(cond::DistBool, then::DistInt, elze::DistInt)
    if isvalid(cond)
        then
    elseif !issat(cond)
        elze
    else
        last_sat_bit = 1 # The fix sets this to 1 instead of 0, so we keep the LSB regardless of its satisfiability
        mbthen, mbelze = max_bits(then), max_bits(elze)
        mb = max(mbthen, mbelze)
        # As many DistBools as the wider argument has
        z = Vector{DistBool}(undef, mb)
        for i=1:mb
            z[i] = if i > mbthen  # If we are beyond the `then` DistInt's width
                !cond & elze.bits[i]
            elseif i > mbelze  # If we are beyond the `else` DistInt's width
                 cond & then.bits[i]
            else  # Common case
                ifelse(cond, then.bits[i], elze.bits[i])
            end
            # Is this bit is satisfiable, then ensure it is included it the returned DistInt
            if issat(z[i])
                last_sat_bit = i
            end
        end
        DistInt(cond.mgr, z[1:last_sat_bit])  # Chop off upper unsatisfiable bits
    end
end
```

This is why the [unit test](https://github.com/Juice-jl/Dice.jl/pull/6/commits/84b9d688eb4df296d6a9259cc06a780b552c45b2) I added fails before the fix: as no bits of `DistInt([DistBool(dicecontext(), false)])` are satisfiable, then the width shrinks to 0.

**Comment by rtjoa** [comment]
> Thanks. I am wondering whether it makes more sense to make the bit width a type parameter and require the same bit width in the then and else branches? @PoorvaGarg ?

I think if we shrink implicitly (as above), then we should also not require the user to explicitly add bits (e.g. to avoid overflow for DistInt addition).

**Reasons to automatically grow/shrink ("arbitrary precision" DistInts):**
- Ergonomics: user does not have to manage widths
- No overflow (it could be worth discussing behavior for div by 0 & NaN values at the same time)

**Reasons to bake width into type**
- If user does not care about execution paths where overflow occurs, this might be able to improve performance beyond what is possible with arbitrary precision DistInts.

**To investigate**
- Effect on performance of automatic shrinking vs. having extra constants in the upper bits. Based on a few tiny experiments, extra constants don't seem to hurt.

I am not sure what discussion has already been had on this topic - are there more reasons for either side that I am missing? I currently feel like the argument for automatically-sized DistInts is stronger - are there motivating examples to include the width in the type?

**Comment by guyvdbroeck** [comment]
The issue with the "prune width if unsat" approach is that it only works with bottom-up BDD compilation in program order. If we want to do any other form of inference or analysis, it will be impossible to determine sat halfway through the program.

**Comment by guyvdbroeck** [comment]
I left this in the issue tracker to discuss the redesign or the integer types: https://github.com/Juice-jl/Dice.jl/issues/10

**Pull request merged**
